# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daycare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phonenum', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('licensed', models.BooleanField()),
                ('opentime', models.IntegerField(max_length=255)),
                ('closetime', models.IntegerField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('ratio', models.CharField(max_length=255)),
                ('security', models.BooleanField()),
                ('food', models.BooleanField()),
                ('waitlist', models.BooleanField()),
                ('avgwait', models.CharField(max_length=255)),
            ],
        ),
    ]
